# Starts the bot at logon WITHOUT administrator rights.
#
#   powershell -ExecutionPolicy Bypass -File deploy\windows\install-startup.ps1
#
# install-task.ps1 registers a proper Scheduled Task, which is the better
# option, but Register-ScheduledTask needs elevation and many users are not
# administrators on their own machine. This drops a launcher in the per-user
# Startup folder instead: it runs at logon, restarts the bot if it exits, and
# needs no special rights.
#
# To remove: delete the file this prints, or run with -Uninstall.

param([switch]$Uninstall)

$ErrorActionPreference = 'Stop'

$botRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
$startup = [Environment]::GetFolderPath('Startup')
$launcher = Join-Path $startup 'start-bybit-bot.cmd'

if ($Uninstall) {
  if (Test-Path $launcher) { Remove-Item $launcher; Write-Host "Removed $launcher" }
  else { Write-Host 'Nothing to remove.' }
  return
}

if (-not (Test-Path (Join-Path $botRoot 'dist\index.js'))) {
  throw "dist\index.js not found. Run 'npm run build' in $botRoot first."
}
if (-not (Test-Path (Join-Path $botRoot '.env'))) {
  throw ".env not found. Run 'npm run setup' in $botRoot first."
}

$body = @"
@echo off
REM Starts the Bybit bot at logon. Generated by install-startup.ps1.
cd /d $botRoot
start "BybitBot" /min cmd /c deploy\windows\run-bot.cmd
"@

Set-Content -Path $launcher -Value $body -Encoding ASCII
Write-Host "Installed $launcher"
Write-Host 'The bot will start at your next logon, in a minimised window.'
Write-Host ''
Write-Host 'A desktop PC still sleeps and reboots. Disable sleep so the bot keeps running:'
Write-Host '  powercfg /change standby-timeout-ac 0'
Write-Host '  powercfg /change hibernate-timeout-ac 0'
