# Reconnects Desktop Commander at every logon, WITHOUT administrator rights.
#
#   powershell -ExecutionPolicy Bypass -File deploy\windows\install-remote-access.ps1
#
# The bot already restarts itself at logon; the link used to watch it did not.
# A reboot therefore produced a machine that traded happily and could not be
# inspected, which is the worst of the two halves to lose: a bot nobody can see
# is a bot nobody can stop.
#
# The launcher loops, so a dropped connection re-establishes itself instead of
# waiting for someone to notice. Ten seconds between attempts is enough to avoid
# hammering a network that is down without leaving a long blind window.
#
# READ THIS BEFORE INSTALLING. This starts a remote-control agent every time you
# log in, and it stays running. That is the point - it is what lets the bot be
# monitored while you are away - but it is a real grant of access to this
# machine, not a background service like any other. Install it only on a machine
# you own and only while you want that access to exist.
#
# To remove: delete the file this prints, or run with -Uninstall. Removing it
# stops the agent from starting next logon; it does not stop one already running.

param([switch]$Uninstall)

$ErrorActionPreference = 'Stop'

$startup = [Environment]::GetFolderPath('Startup')
$launcher = Join-Path $startup 'start-desktop-commander.cmd'

if ($Uninstall) {
  if (Test-Path $launcher) { Remove-Item $launcher; Write-Host "Removed $launcher" }
  else { Write-Host 'Nothing to remove.' }
  Write-Host 'A Desktop Commander already running is unaffected; close its window to stop it.'
  return
}

$body = @"
@echo off
REM Keeps Desktop Commander connected. Generated by install-remote-access.ps1.
REM Delete this file to stop it starting at logon.
:loop
npx @wonderwhy-er/desktop-commander@latest remote
timeout /t 10 /nobreak >nul
goto loop
"@

Set-Content -Path $launcher -Value $body -Encoding ASCII
Write-Host "Installed $launcher"
Write-Host ''
Write-Host 'Desktop Commander will reconnect at every logon, in a minimised window,'
Write-Host 'and retry every 10 seconds if the connection drops.'
Write-Host ''
Write-Host 'This is remote access to this machine. Delete that file to withdraw it.'
