import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  ListToolsRequestSchema,
  CallToolRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import { zodToJsonSchema } from 'zod-to-json-schema';
import { ZodError, type ZodTypeAny } from 'zod';
import { checkVersionForTool } from './version-check.js';
import { resolveSignConfig } from './utils/auth.js';
import { subscriptionTools } from './tools/subscription/index.js';

// allTools is generated by the codegen pipeline.
// If the file doesn't exist yet, we fall back to an empty array so the server
// still starts (useful before the first `npm run generate`).
let allTools: Array<{
  name: string;
  description: string;
  inputSchema: ZodTypeAny;
  /** MCP tool annotations (readOnlyHint/destructiveHint/openWorldHint) baked in by the generator. */
  annotations?: Record<string, boolean>;
  handler: (input: Record<string, unknown>) => Promise<unknown>;
}> = [];

try {
  const mod = await import('./tools/index.js');
  allTools = mod.allTools ?? [];
} catch {
  // No tools generated yet — server starts with empty tool list.
}
// subscriptionTools are hand-written (not generated). The generated tools/index.ts
// already includes them, so only append the ones not already present — this keeps
// them available in the pre-generation fallback path without double-registering.
allTools = [
  ...allTools,
  ...subscriptionTools.filter((s) => !allTools.some((t) => t.name === s.name)),
];

export async function startServer(): Promise<void> {
  const server = new Server(
    { name: 'trading-mcp', version: '2.1.20' },
    { capabilities: { tools: {} } },
  );

  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: allTools.map((tool) => ({
      name: tool.name,
      description: tool.description,
      inputSchema: zodToJsonSchema(tool.inputSchema, { target: 'openApi3' }),
      // Pass through generator-baked annotations. These are hints only; a host must choose to
      // honor them. Omitted for hand-written tools that don't declare any.
      ...(tool.annotations ? { annotations: tool.annotations } : {}),
    })),
  }));

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const { name, arguments: args } = request.params;
    const tool = allTools.find((t) => t.name === name);

    if (!tool) {
      return {
        content: [{ type: 'text', text: `Tool not found: ${name}` }],
        isError: true,
      };
    }

    try {
      const versionError = await checkVersionForTool();
      if (versionError) {
        return {
          content: [{ type: 'text', text: versionError }],
          isError: true,
        };
      }

      const parsed = tool.inputSchema.parse(args ?? {});
      const result = await tool.handler(parsed);
      return {
        content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
      };
    } catch (err) {
      const msg =
        err instanceof ZodError
          ? `Validation error: ${err.errors.map((e) => `${e.path.join('.') || 'input'}: ${e.message}`).join('; ')}`
          : `Error: ${(err as Error).message}`;
      return {
        content: [{ type: 'text', text: msg }],
        isError: true,
      };
    }
  });

  const transport = new StdioServerTransport();
  await server.connect(transport);

  let authMode = 'unauthenticated';
  if (process.env.BYBIT_API_KEY) {
    try {
      const signConfig = resolveSignConfig();
      authMode = signConfig.type === 'rsa' ? 'RSA-SHA256' : 'HMAC-SHA256';
    } catch (e) {
      authMode = `config error — ${e instanceof Error ? e.message : String(e)}`;
    }
  }
  console.error(`trading-mcp started — ${allTools.length} tool(s) registered, auth: ${authMode}`);
}
